# Generated by Django 2.0.1 on 2018-01-17 09:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author_id', models.CharField(max_length=50)),
                ('parent_id', models.IntegerField(null=True)),
                ('step', models.CharField(max_length=6)),
                ('week_number', models.SmallIntegerField()),
                ('step_number', models.SmallIntegerField()),
                ('text', models.TextField()),
                ('timestamp', models.DateTimeField()),
                ('moderated', models.DateTimeField(null=True)),
                ('likes', models.SmallIntegerField()),
                ('course_name', models.CharField(max_length=255)),
                ('course_run', models.SmallIntegerField()),
                ('word_count', models.SmallIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='CommentTerms',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wordcloud.Comment')),
            ],
        ),
        migrations.CreateModel(
            name='LTIConsumer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('consumer_key', models.CharField(max_length=255, unique=True)),
                ('secret', models.CharField(max_length=36)),
            ],
        ),
        migrations.CreateModel(
            name='StopWord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('word', models.CharField(max_length=24, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Term',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('term', models.CharField(max_length=255, unique=True)),
                ('category', models.CharField(max_length=30)),
                ('score', models.SmallIntegerField()),
            ],
        ),
        migrations.AddField(
            model_name='commentterms',
            name='term',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wordcloud.Term'),
        ),
        migrations.AlterUniqueTogether(
            name='commentterms',
            unique_together={('comment', 'term')},
        ),
    ]
