# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-14 17:46
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author_id', models.CharField(max_length=50)),
                ('parent_id', models.IntegerField()),
                ('step', models.CharField(max_length=6)),
                ('week_number', models.SmallIntegerField()),
                ('step_number', models.SmallIntegerField()),
                ('text', models.TextField()),
                ('timestamp', models.DateTimeField()),
                ('moderated', models.DateTimeField()),
                ('likes', models.SmallIntegerField()),
                ('course_name', models.CharField(max_length=255)),
                ('course_run', models.SmallIntegerField()),
                ('word_count', models.SmallIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='CommentTerms',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wordcloud.Comment')),
            ],
        ),
        migrations.CreateModel(
            name='Term',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('term', models.CharField(max_length=255)),
                ('category', models.CharField(max_length=30)),
                ('score', models.SmallIntegerField()),
            ],
        ),
        migrations.AddField(
            model_name='commentterms',
            name='term_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wordcloud.Term'),
        ),
    ]
