# Generated by Django 2.0.1 on 2018-01-17 09:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wordcloud', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='term',
            name='category',
        ),
        migrations.RemoveField(
            model_name='term',
            name='score',
        ),
    ]
