# Generated by Django 2.0.1 on 2018-01-17 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wordcloud', '0002_auto_20180117_0942'),
    ]

    operations = [
        migrations.AddField(
            model_name='commentterms',
            name='count',
            field=models.SmallIntegerField(default=1),
            preserve_default=False,
        ),
    ]
