# Generated by Django 2.0.1 on 2018-01-17 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wordcloud', '0003_commentterms_count'),
    ]

    operations = [
        migrations.CreateModel(
            name='CourseLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.CharField(max_length=36, unique=True)),
                ('return_url', models.CharField(max_length=255)),
                ('course_id', models.CharField(max_length=255)),
                ('access_time', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='UserAccess',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.CharField(max_length=36, unique=True)),
                ('count', models.IntegerField()),
                ('last_access', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
