# Generated by Django 2.0.1 on 2018-01-17 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wordcloud', '0004_courselog_useraccess'),
    ]

    operations = [
        migrations.AlterField(
            model_name='courselog',
            name='user_id',
            field=models.CharField(max_length=36),
        ),
    ]
