# Generated by Django 2.0.1 on 2018-01-18 12:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wordcloud', '0005_auto_20180117_1753'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='StopWord',
            new_name='BadWord',
        ),
    ]
