# Generated by Django 2.0.1 on 2018-01-18 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wordcloud', '0006_auto_20180118_1249'),
    ]

    operations = [
        migrations.CreateModel(
            name='SearchLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.CharField(max_length=36)),
                ('search', models.CharField(max_length=255)),
                ('course_name', models.CharField(max_length=255)),
                ('course_run', models.SmallIntegerField()),
            ],
        ),
    ]
