# Generated by Django 2.0.1 on 2018-01-18 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wordcloud', '0008_auto_20180118_1738'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useraccess',
            name='count',
            field=models.IntegerField(default=0),
        ),
    ]
