# Generated by Django 2.0.1 on 2018-01-26 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wordcloud', '0009_auto_20180118_1739'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='source_id',
            field=models.CharField(default='abc', max_length=255),
            preserve_default=False,
        ),
    ]
