# Generated by Django 2.0.7 on 2018-08-01 14:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wordcloud', '0012_clicklog'),
    ]

    operations = [
        migrations.CreateModel(
            name='CommentHashtag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count', models.SmallIntegerField()),
                ('comment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wordcloud.Comment')),
            ],
        ),
        migrations.CreateModel(
            name='Hashtag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hashtag', models.CharField(max_length=255, unique=True)),
            ],
        ),
        migrations.AddField(
            model_name='commenthashtag',
            name='hashtag',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wordcloud.Hashtag'),
        ),
        migrations.AlterUniqueTogether(
            name='commenthashtag',
            unique_together={('comment', 'hashtag')},
        ),
    ]
