# Generated by Django 2.0.7 on 2018-08-01 14:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wordcloud', '0013_auto_20180801_1402'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='CommentHashtag',
            new_name='CommentHashtags',
        ),
    ]
